### ISSUE TITLE
Requirement Analysis

### ISSUE THREAD

**Issue by hienlh** [hienlh/LuhihiCb#4]
**Acceptance criteria**
- Have doc file about Requirement Analysis

**Comment by caoluyennguyen** [comment]
### 1. Hiện trạng:
- Nhu cầu tìm kiếm nửa còn lại càng ngày càng phổ biến tại tần suất làm việc quá lớn và sự ảnh hưởng bởi công nghệ làm con người ngại tiếp xúc trực tiếp.
### 2. Các quy trình nghiệp vụ:
- Cập nhật hình ảnh cá nhân
- Xem ảnh cá nhân ngẫu nhiên của người khác (Không biết ảnh của ai) 
- Bày tỏ cảm xúc với ảnh của người khác (Có 2 thể hiện Thích hoặc Bỏ qua) 
+ Thích: Sẽ gửi thông báo cho đối phương.
+ Bỏ qua: Tiếp tục xem ảnh của người khác. 
- Thông báo khi có người thích ảnh cá nhân của mình (Thông báo bao gồm ảnh của cá nhân của người thích) => Có 2 phương án xử lý : 
+ Chấp nhận trò chuyện: Tạo không gian chat riêng giữa 2 người. 
+ Bỏ qua: Tiếp tục xem ảnh.
 - Sau khi chấp nhận trò chuyện thì sẽ gửi link facebook cho đối phương.
### 3. Công nghệ sử dụng: 
- Nodejs 
- ExpressJS 
- Facebook messenger platform
- TypeOrm
- Heroku
